In [11]:
#practicing regressions

import sys
import numpy as np
from io import *
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt

x = np.arange(10).reshape(-1, 1)
y = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

print(x)
print(y)

model = LogisticRegression(solver='liblinear', random_state=0)

model.fit(x, y)

model.classes_

model.predict_proba(x)

model.score(x,y)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[0 0 0 0 1 1 1 1 1 1]


0.9

In [14]:
arr = np.arange(12) + 1
print(arr)
mask = np.ones(len(arr), dtype=bool)
print(mask)

mask[[0,2,4]] = False
print(mask)
result = arr[mask,...]

print(result)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ True  True  True  True  True  True  True  True  True  True  True  True]
[False  True False  True False  True  True  True  True  True  True  True]
[ 2  4  6  7  8  9 10 11 12]
